### ISSUE TITLE
NAV: remove "pressed" state

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#10]
Type hover is probably all that's needed. I like the green. Can remove the blue that happens on click.

![screen shot 2016-06-29 at 9 59 49 am](https://cloud.githubusercontent.com/assets/5384728/16457204/3ab2e536-3de0-11e6-8fdc-f497c1ce6ceb.png)

**Comment by jakewelchert** [comment]
Resolved.
