### ISSUE TITLE
FOOTER: email sign up text too low

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#13]
and on Firefox responsive views it disappears.

![screen shot 2016-06-29 at 10 03 35 am](https://cloud.githubusercontent.com/assets/5384728/16457385/ef8e2b28-3de0-11e6-8dcd-1b0817440e46.png)
![screen shot 2016-06-29 at 10 04 20 am](https://cloud.githubusercontent.com/assets/5384728/16457386/ef908cec-3de0-11e6-82a1-0a660a234aa4.png)

**Comment by jakewelchert** [comment]
Resolved. There's a button alignment issue on Firefox but I'll fix when I can restructure it.
