### ISSUE TITLE
BASIC PAGE: increase page title size

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#20]
Compared to the landing pages, they look small. For example:

News & Events vs. What's A Healthy Home

![screen shot 2016-07-09 at 4 07 35 pm](https://cloud.githubusercontent.com/assets/5384728/16710303/5f939c58-45ef-11e6-9dc7-ddae6a3c08b4.png)
![screen shot 2016-07-09 at 4 07 31 pm](https://cloud.githubusercontent.com/assets/5384728/16710304/5fa7dede-45ef-11e6-9cd1-2c589f5fbab7.png)

**Comment by jakewelchert** [comment]
Resolved.
