### ISSUE TITLE
HOMEPAGE: use typographer marks for apostrophes

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#21]
’ rather than '

![screen shot 2016-07-09 at 4 09 22 pm](https://cloud.githubusercontent.com/assets/5384728/16710315/a576c54c-45ef-11e6-89c5-6019cd88bfff.png)

**Comment by justinkemerling** [comment]
children’s
What’s

**Comment by jakewelchert** [comment]
Resolved.
