### ISSUE TITLE
ALERT BAR: text could be a little higher

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#22]
The text feels a little low in the space of the orange bar.

![screen shot 2016-07-09 at 4 11 43 pm](https://cloud.githubusercontent.com/assets/5384728/16710325/eddd30dc-45ef-11e6-8623-b477e1ff88a3.png)

**Comment by jakewelchert** [comment]
Resolved. Let me know how you're feeling.

**Comment by justinkemerling** [comment]
Yes indeed.
