### ISSUE TITLE
CONTACT PAGE: implement approved contact page

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#23]
![jkdc_ohka-website_design-basiccontact](https://cloud.githubusercontent.com/assets/5384728/16710337/561fb0d4-45f0-11e6-8479-b4a17a829b1b.png)

**Comment by justinkemerling** [comment]
On Dropbox: ohka_mapicon.svg

**Comment by jakewelchert** [comment]
Created. Need to finish styling and edit the colors of the map.

**Comment by jakewelchert** [comment]
Resolved.
