### ISSUE TITLE
BLOG: Featured posts updates

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#24]
Category Text: make these white, add commas to separate 2 or more
Button: make the button color white w/ green text

![screen shot 2016-07-09 at 4 47 27 pm](https://cloud.githubusercontent.com/assets/5384728/16710465/f7c27094-45f4-11e6-92e3-64bdba24f546.png)

**Comment by justinkemerling** [comment]
how you currently have the vertical height working w/ the text in the image space works great. the mockups show the image not getting larger if the headline goes to more than 1 line. what are your thoughts on that? i'm fine keeping it how you have it.

**Comment by jakewelchert** [comment]
Resolved. I'll need to figure out a way to treat the comma with multiple categories.

**Comment by justinkemerling** [comment]
No worries on the commas. We're good as is!
