### ISSUE TITLE
BLOG: spacing and text size updates for the tan panels

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#25]
- Smaller headline + description text (can go smaller on homepage too)
- 64px left margin and above the headline
- type width goes to 648px
- 24px of space between headline and description
- 180px round thumbnail (which is bigger than the homepage)
- 40px margin above and to the right
- 40px of space between each entry

![screen shot 2016-07-09 at 4 50 59 pm](https://cloud.githubusercontent.com/assets/5384728/16710478/55feb9c4-45f5-11e6-9d0d-2f88a3850a88.png)

**Comment by justinkemerling** [comment]
Can probably ditch the horizontal rule between featured and regular posts.

**Comment by jakewelchert** [comment]
I'm thinking we should should put that category name above the title. Very small. We can chat about it in the morning.

**Comment by jakewelchert** [comment]
Resolved. Please review and let me know how you're feeling.
