### ISSUE TITLE
LANDING PAGE: make bottom "Learn More" graphic wider to 1000px

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#26]
On the landing pages, if the page width was 1000px that'd be idea. The bottom image that takes you to the next page would need to be wider (1000px) and the text in the callouts would be left aligned. I think they're too far to the left currently. 

![screen shot 2016-07-10 at 8 09 28 am](https://cloud.githubusercontent.com/assets/5384728/16715548/c101505c-46a8-11e6-8d52-3a8fe43dcfc3.png)

**Comment by jakewelchert** [comment]
Updated bottom image, but would like to review overall page width with you to confirm before making change.

**Comment by justinkemerling** [comment]
From our discussion, here that bottom image would be the same width as the page image:

![screen shot 2016-07-12 at 8 44 22 am](https://cloud.githubusercontent.com/assets/5384728/16769122/e318ed0c-480c-11e6-933c-6341740347bb.png)
![screen shot 2016-07-12 at 8 44 31 am](https://cloud.githubusercontent.com/assets/5384728/16769123/e32bccd8-480c-11e6-85f4-fd11c65b92f7.png)

**Comment by jakewelchert** [comment]
Resolved. Will work on lining up the staggered callout type to this.
