### ISSUE TITLE
LANDING PAGE: move icons closer to the intro text

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#27]
They seem a little far away as of now.

![screen shot 2016-07-10 at 2 18 20 pm](https://cloud.githubusercontent.com/assets/5384728/16715566/3a24ca86-46a9-11e6-9290-6e18fe206225.png)

**Comment by jakewelchert** [comment]
Resolved. Review and let me know how you're feeling.

**Comment by justinkemerling** [comment]
Nice.
