### ISSUE TITLE
DONATION PAGE: implement basic page

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#29]
It will just be basic text, and a big button to go to PayPal:

http://www.omahahealthykids.org

**Comment by jakewelchert** [comment]
Added. I added an a Button field to craft for instances like this...spacing seems a bit funny to me but we have a few options for making a fix. Can review tomorrow.

**Comment by justinkemerling** [comment]
I'll discuss this w/ Halie when she come in to review.
