### ISSUE TITLE
RWD: full-width margins

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#30]
Might be good to go full width for a lot of the element when we get down to mobile. This homepage mockup would also be good for the News & Events page. Reducing the headline text and giving it more room to wrap nicely:

![screen shot 2016-07-10 at 3 07 00 pm](https://cloud.githubusercontent.com/assets/5384728/16715803/fa893220-46af-11e6-9ea0-13a793fec4fc.png)

**Comment by jakewelchert** [comment]
Made this change on the News & Events listing page. Please review there and if you like it I'll make the change everywhere else. Feels good to me, but wondering if we change that header box with the pattern full-width too?

**Comment by jakewelchert** [comment]
Resolved throughout site. Let me know how you're feeling about it.

**Comment by justinkemerling** [comment]
Good to go!
