### ISSUE TITLE
RWD: homepage kids middle display

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#31]
Maybe there's another variation when the kids move to the left of the text.

From desktop:
- 75% Kid
- 50% What/Why/How
- 2 column down the middle

![screen shot 2016-07-10 at 3 19 12 pm](https://cloud.githubusercontent.com/assets/5384728/16715867/ea8c98a6-46b1-11e6-93bf-4a61967b4b50.png)

**Comment by jakewelchert** [comment]
Resolved. Let me know how you're feeling.

**Comment by justinkemerling** [comment]
yeah! looking real good. couple things:
- Phone site: keep the text left align, not wrapping weird
- 'How' left aligned? So it overlaps the gray here.

![screen shot 2016-07-12 at 1 17 41 pm](https://cloud.githubusercontent.com/assets/5384728/16778405/7c2d318a-4833-11e6-93ea-6c6b7e34bfa3.png)
![screen shot 2016-07-12 at 1 19 21 pm](https://cloud.githubusercontent.com/assets/5384728/16778406/7c43cf58-4833-11e6-9100-e8fb50417dda.png)

**Comment by jakewelchert** [comment]
Resolved.
