### ISSUE TITLE
RWD: landing page staggered callouts adjustment

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#32]
I know these are tricky too, in terms of mobile and tablet, possible to keep the image orientation the whole time? Maybe it's not tied to the gray and we make the gray full width to give us some extra room to work with. 

![screen shot 2016-07-10 at 3 30 34 pm](https://cloud.githubusercontent.com/assets/5384728/16715908/4a1d2ffa-46b3-11e6-8ca2-7f204509bd26.png)

![screen shot 2016-07-10 at 3 28 55 pm](https://cloud.githubusercontent.com/assets/5384728/16715909/4e18eac2-46b3-11e6-889f-1826b4c90c7a.png)

![screen shot 2016-07-10 at 3 29 09 pm](https://cloud.githubusercontent.com/assets/5384728/16715910/51d0b8de-46b3-11e6-9f94-94bdc9443052.png)

**Comment by justinkemerling** [comment]
Last one shows a tighter column w/ the gray showing below the bottom of the image.

**Comment by jakewelchert** [comment]
I've placed a test of this in the Visual Landing Page layouts for you to see how it looks when built with inline images that scale. It's getting closer. More responsive tweaks and edits to the border and I think it's there. We can review it together in the morning.

**Comment by justinkemerling** [comment]
Getting there! Try this size image for that space: 420 x 524 (slightly smaller than the 480 x 540 current size)

![ohka_how_policy](https://cloud.githubusercontent.com/assets/5384728/16767275/4474a414-4804-11e6-9c7e-6b130a0ada91.jpg)

**Comment by jakewelchert** [comment]
As discussed, looks good on mobile and desktop. Will make better adjustments on middle screens.

**Comment by jakewelchert** [comment]
Made adjustments to middle screens. Will swap out border image and should be good to go.

**Comment by jakewelchert** [comment]
Resolved. Swapped out for proper border image.
