### ISSUE TITLE
RWD: drawer updates

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#33]
- Make buttons white w/ green text instead of orange
- No orange hover

![screen shot 2016-07-09 at 4 20 40 pm](https://cloud.githubusercontent.com/assets/5384728/16715925/b64fd9a2-46b3-11e6-9d47-31a28e1d5ad4.png)

**Comment by jakewelchert** [comment]
Resolved. Review and let me know how you feel.

**Comment by justinkemerling** [comment]
Close X still has the orange. Otherwise good to go.

![screen shot 2016-07-11 at 8 24 29 am](https://cloud.githubusercontent.com/assets/5384728/16732077/f07dd830-4740-11e6-872f-c0152d15960b.png)

**Comment by jakewelchert** [comment]
Resolved.
