### ISSUE TITLE
RWD: footer updates

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#34]
- I'd lose those horizontal rules
- Email signup buttons moves below the field
- Text doesn't show up

![screen shot 2016-07-10 at 3 34 36 pm](https://cloud.githubusercontent.com/assets/5384728/16715934/e9ebd478-46b3-11e6-82ec-2b997b2ae53b.png)
![screen shot 2016-07-10 at 3 34 44 pm](https://cloud.githubusercontent.com/assets/5384728/16715935/ea052914-46b3-11e6-8a6d-174e4b26c18d.png)

**Comment by jakewelchert** [comment]
Got rid of horizontal rules. The button and hidden text issue is probably through Firefox. Try a hard refresh and it should be better. We can review together tomorrow.
