### ISSUE TITLE
SPELLING: text updates from Halie

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#36]
- On the three links at the top, "Why Healthy Homes Matter in Omaha" -- Healthy is missing the Y.
- Menu in the footer -- "Healthy" is spelled wrong on the "Why Healthy Homes Matter" piece.
- We decided that we won't be needing a "Volunteer" page. So, that link in the footer can be taken out.
- Also, I'd like to write a new testimonial, so if you could take mine out, for now, that'd be great. Thanks!

**Comment by jakewelchert** [comment]
Resolved.
