### ISSUE TITLE
BLOG: Featured not working correctly

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#40]
Currently, "Featured Posts" are always being shown. We only want "Featured Posts" to show if the toggle is clicked. When the toggle is clicked, up to 2 posts can be featured at the top of Page 1. 

The default should be Latest Post Date shows up first. All other posts descend back from there. 

At one point, the oldest Post I created was being featured at the top. 

At another point toggle a Featured Post off doesn't remove it from the top.

**Comment by jakewelchert** [comment]
This main issue here should be fixed. Now select some posts to be 'featured' and they should show up in order.

Need to exclude from secondary feed below, as well as the "Related Posts" in an individual blog post. Will fix on Friday.

**Comment by jakewelchert** [comment]
"Featured Posts" are now excluded from the secondary pagination feed and no longer show up on the second page.
