### ISSUE TITLE
CONTACT - finish map and forms

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/omahahealthykidsalliance#41]
Finish styling map and add info capture for forms.

**Comment by jakewelchert** [comment]
Map styling updated.
Need to add capture for forms.

**Comment by justinkemerling** [comment]
Lookin' good. If the Address and the Map Icon could link to Google Maps, that'd be awesome.

![screen shot 2016-07-16 at 4 38 08 pm](https://cloud.githubusercontent.com/assets/5384728/16915604/19f0135e-4cbe-11e6-8d11-1e529f06dd9f.png)

**Comment by jakewelchert** [comment]
Resolved.
