### ISSUE TITLE
ABOUT US: Style Updates

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#43]
- Add styling for the Subhead Header
- Increase size of the Callout Header
- Move Text down in relation to the image.

![screen shot 2016-07-15 at 11 26 14 am](https://cloud.githubusercontent.com/assets/5384728/16881291/28d59bfa-4a7f-11e6-8f90-dd25213635c2.png)

**Comment by jakewelchert** [comment]
Resolved.
