### ISSUE TITLE
WHY WE DO THIS: make quote text size bigger

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#44]
Just a couple options. Halie thought it was a little small.

![screen shot 2016-07-15 at 11 28 30 am](https://cloud.githubusercontent.com/assets/5384728/16881337/57300cf6-4a7f-11e6-98e3-1ed19352bf28.png)

**Comment by jakewelchert** [comment]
Resolved. Let me know how you're feeling about this size.
