### ISSUE TITLE
SITE: Add Instagram account to social

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#46]
Header + Footer

https://www.instagram.com/omahahealthykids/

![screen shot 2016-07-15 at 11 37 36 am](https://cloud.githubusercontent.com/assets/5384728/16881597/8f7ddc04-4a80-11e6-839c-1b71380f1871.png)
![screen shot 2016-07-15 at 11 37 32 am](https://cloud.githubusercontent.com/assets/5384728/16881598/8f8d8cee-4a80-11e6-96fe-8a5a412de424.png)

**Comment by jakewelchert** [comment]
Resolved.
