### ISSUE TITLE
VIMEO: add ability to embed videos on posts/pages

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#47]
In progress, but no video showing up:
http://104.131.188.200/index.php/newsandevents/2016/the-off-kilter-filter-video

Vimeo link:
https://vimeo.com/163839122

**Comment by jakewelchert** [comment]
Resolved. Changed how the entries clean up the HTML which was getting rid of <iframe>'s. Need to copy full link with https: from Vimeo or Youtube.
