### ISSUE TITLE
HOMEPAGE: add Page Title field for the homepage mission statement

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#48]
In Craft so they can edit. They also want to link something in the words. Setup similar to the Landing pages. Also need to control where "Learn More" goes.

![screen shot 2016-07-15 at 11 54 07 am](https://cloud.githubusercontent.com/assets/5384728/16882096/d801a4b8-4a82-11e6-8a1d-8b4399d07c86.png)

![screen shot 2016-07-15 at 11 53 20 am](https://cloud.githubusercontent.com/assets/5384728/16882082/cc6e34ae-4a82-11e6-910a-1ce86d057198.png)

**Comment by jakewelchert** [comment]
Resolved.
