### ISSUE TITLE
BLOG: styles list text to be the same size as body copy

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#49]
It's a little big as of now.

![screen shot 2016-07-12 at 3 00 15 pm](https://cloud.githubusercontent.com/assets/5384728/16885550/b5674856-4a94-11e6-9150-508a151a6924.png)

**Comment by jakewelchert** [comment]
When you get a minute can you point me to this post? It'll make it easier for me to find out which list style to edit.

**Comment by justinkemerling** [comment]
There's actually 2 instances; on a Landing Page and then on the Posts:

http://104.131.188.200/index.php/whats-a-healthy-home
http://104.131.188.200/index.php/resources/lead-poisoning-prevention

The styles could be the same for this, and responsive on the size reduction. 

![screen shot 2016-07-18 at 7 56 17 am](https://cloud.githubusercontent.com/assets/5384728/16915469/45bea0f0-4cbd-11e6-9696-5a11e5000735.png)
![screen shot 2016-07-18 at 7 57 15 am](https://cloud.githubusercontent.com/assets/5384728/16915470/45d1d81e-4cbd-11e6-8db3-321bd91ccfab.png)

**Comment by justinkemerling** [comment]
The other link is to Training:
http://104.131.188.200/index.php/training

**Comment by jakewelchert** [comment]
Resolved. We can style these anyway you'd like, so if you have additional edits we can discuss when you're at the office.

**Comment by jakewelchert** [comment]
Resolved. Feel free to let me know about any H# edits.
