### ISSUE TITLE
NAV: use typographer marks for Nav items

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#56]
What’s A Healthy Home

![screen shot 2016-07-19 at 9 51 09 am](https://cloud.githubusercontent.com/assets/5384728/16954457/8c5e6764-4d96-11e6-933a-170b5c0c258c.png)
![screen shot 2016-07-19 at 9 51 14 am](https://cloud.githubusercontent.com/assets/5384728/16954458/8c5eb606-4d96-11e6-9d4d-a52b4138c7cf.png)

**Comment by jakewelchert** [comment]
Resolved.
