### ISSUE TITLE
HOMEPAGE: add editable Entries for What, Why, How

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#57]
- Title
- Decription
- Link Text
- Link URL
- Image (w/ exact size specs for 2X)

![screen shot 2016-07-19 at 9 50 07 am](https://cloud.githubusercontent.com/assets/5384728/16954542/d524f5c6-4d96-11e6-8d95-b6bb2c08f960.png)

**Comment by jakewelchert** [comment]
Resolved.
