### ISSUE TITLE
CATEGORIES: fix sorting

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#58]
For News & Events and Resource, sorting isn't working. Halie wants it to be that if you click on Stories you only see the Stories Category. 

For example: http://104.131.188.200/index.php/newsandevents/announcements

You'd only see Announcements on this.

**Comment by jakewelchert** [comment]
Resolved. Will add back in pagination for these too.

**Comment by jakewelchert** [comment]
Resolved with pagination added back in for category pages.
