### ISSUE TITLE
CATEGORIES: update dropdown? 

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#59]
All Posts
Category Name 1
Category Name 2
Category Name 3

maybe we go w/ those? and if you select one it shows that in the display?

![screen shot 2016-07-16 at 2 02 17 pm](https://cloud.githubusercontent.com/assets/5384728/16963705/62ca04e0-4dbd-11e6-8aab-10aaceb22f57.png)

**Comment by jakewelchert** [comment]
News & Events and Resources should say Select A Category.

**Comment by jakewelchert** [comment]
Resolved.
