### ISSUE TITLE
404: add design from OHKA crew

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#61]
PNG at 2X size of that sketch:

<img width="660" alt="ohka-image-404" src="https://cloud.githubusercontent.com/assets/5384728/16992689/f83da1d2-4e65-11e6-8c01-ceca8e509e79.png">

![jkdc_ohka-website_design-basic-404](https://cloud.githubusercontent.com/assets/5384728/16992676/e7049cc2-4e65-11e6-89e0-53e57b5de0b9.png)

**Comment by jakewelchert** [comment]
Resolved.
