### ISSUE TITLE
SOCIAL LINKS: center the smaller icons in the circles 

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#63]
On the homepage these look a little high. The footer icons look perfect:

<img width="479" alt="screen shot 2016-07-21 at 3 28 03 pm" src="https://cloud.githubusercontent.com/assets/5384728/17157493/4f465890-5355-11e6-8a0a-418580ac88eb.png">

**Comment by jakewelchert** [comment]
Resolved.
