### ISSUE TITLE
PAGINATION: update look to Pills/Circles

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#64]
And then remove First/Last. 

W/ the 3 dots, Western Values Project works well:

<img width="404" alt="screen shot 2016-07-26 at 5 23 17 pm" src="https://cloud.githubusercontent.com/assets/5384728/17157552/cb4fdec0-5355-11e6-8df3-3a79778a0365.png">

**Comment by jakewelchert** [comment]
Updated to #ddd pills and active state is now green. Hover is darker green for all. I think that's what we discussed? Let me know what you think.

Also, with the ellipsis...I'm still looking at how to include those in a loop in Craft.

**Comment by jakewelchert** [comment]
Resolved.
