### ISSUE TITLE
BASIC PAGE: CTA spacing looks a little off

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#72]
Too much space above the button, not enough below:

http://104.131.188.200/index.php/omaha-lead-registry

This feels nice when the button is above the text:

http://104.131.188.200/index.php/donate

![screen shot 2016-08-16 at 2 44 15 pm](https://cloud.githubusercontent.com/assets/5384728/17751926/08d4b0b4-648f-11e6-8dc2-aa9fe1268a23.png)

**Comment by jakewelchert** [comment]
Resolved.
