### ISSUE TITLE
BUTTONS: change "Training" to "Services"

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#73]
I've changed the page title, but the buttons in the header and the footer need to change to link to that new page:

![screen shot 2016-08-23 at 9 35 13 am](https://cloud.githubusercontent.com/assets/5384728/17896193/3e282e96-6915-11e6-9e2a-365b1828ab1d.png)
![screen shot 2016-08-23 at 9 35 17 am](https://cloud.githubusercontent.com/assets/5384728/17896194/3e3b4c74-6915-11e6-8b4e-d08ee4011c91.png)

**Comment by jakewelchert** [comment]
Resolved.
