### ISSUE TITLE
RWD: left staggered inset image breaking out of the frame

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#75]
that pesky image stuff:

![2016-09-12 08 40 11](https://cloud.githubusercontent.com/assets/5384728/18438299/5d3dd176-78c6-11e6-916f-8f68f419e4da.png)
![2016-09-12 08 39 59](https://cloud.githubusercontent.com/assets/5384728/18438300/5d576fbe-78c6-11e6-998c-8f66a98fc94d.png)

**Comment by jakewelchert** [comment]
Resolved.
