### ISSUE TITLE
MOBILE: button gets funky on this CTA

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#77]
http://104.131.188.200/index.php/about-us

![2016-09-12 08 37 41](https://cloud.githubusercontent.com/assets/5384728/18438372/b06114ee-78c6-11e6-8f97-fcd829e5da59.png)

**Comment by jakewelchert** [comment]
Resolved. Reduced right and left padding on all mobile buttons so they're all similar.
