### ISSUE TITLE
MOBILE: email button still a little wonky

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#78]
![screen shot 2016-09-12 at 8 56 13 am](https://cloud.githubusercontent.com/assets/5384728/18438501/4691143c-78c7-11e6-9a35-aab58e5dc68b.png)

![2016-09-12 08 38 20](https://cloud.githubusercontent.com/assets/5384728/18438506/4abd1fb0-78c7-11e6-852c-bdedd33ba23c.png)

**Comment by jakewelchert** [comment]
Resolved. Made svg icon instead of live type and added better confirmation & required text language.
