### ISSUE TITLE
TABLET: homepage too wide

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#79]
something breaks on iPad where the width of the homepage can slide left/right. see the white margin here on the right:

![2016-09-12 08 39 23](https://cloud.githubusercontent.com/assets/5384728/18438708/15dd95a8-78c8-11e6-908b-3a719615d1c3.png)

**Comment by jakewelchert** [comment]
Resolved. Was a padding issue.
