### ISSUE TITLE
TABLET: What's Next tiles are colliding

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#81]
Example: 

http://104.131.188.200/index.php/newsandevents/2016/davids-story

![2016-09-12 08 41 07](https://cloud.githubusercontent.com/assets/5384728/18438783/62488b5a-78c8-11e6-876d-0e40a47c12b5.png)

**Comment by jakewelchert** [comment]
Resolved.
