### ISSUE TITLE
ODD: sometimes site elements don't load

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#82]
Occasionally, as navigating around, the site can show up this way. Thoughts?

![2016-09-12 08 39 42](https://cloud.githubusercontent.com/assets/5384728/18438821/89e79a02-78c8-11e6-9a75-767af2b7a498.png)

**Comment by jakewelchert** [comment]
Resolved. It was a Typekit issue. Let me know if you see it again on iPad.
