### ISSUE TITLE
BLOG: 'What's Next' tiles should be Category Related

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#83]
currently, I think it's just in chronological:

http://104.131.188.200/index.php/resources/radon

![screen shot 2016-09-12 at 9 10 12 am](https://cloud.githubusercontent.com/assets/5384728/18438865/ba0879f4-78c8-11e6-9ff3-df48a2b1ce83.png)

**Comment by jakewelchert** [comment]
What's next should be by categories. Check if chronological within a category is available. You're on post 3, then 4 and 5 show up.

**Comment by jakewelchert** [comment]
Should be resolved. Resources is a little wonky, but I think it's because a lot of them were posted on the same day. We can review it together.

**Comment by jakewelchert** [comment]
Resolved.
