### ISSUE TITLE
BLOG: what's the difference between Featured One and Two?

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#84]
Which one puts it on the homepage? 

![screen shot 2016-09-12 at 9 12 12 am](https://cloud.githubusercontent.com/assets/5384728/18438943/018f1f1c-78c9-11e6-8ecd-0098d83d4b39.png)

**Comment by jakewelchert** [comment]
Pull Featured to Homepage

**Comment by jakewelchert** [comment]
These have to be Featured Posts, so if there's only one selected...that's what will show up.

**Comment by jakewelchert** [comment]
Change homepage back to chronological.

**Comment by jakewelchert** [comment]
Resolved.
