### ISSUE TITLE
GLOBALS: add share graphic fields and Analytics field

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/omahahealthykidsalliance#85]
Hey buddy. On the Flagship stuff, Cody setup Global to have some SEO stuff for sharing and then Analytics. Possible on this? 

![screen shot 2016-09-14 at 5 43 21 pm](https://cloud.githubusercontent.com/assets/5384728/18532616/db526968-7aa2-11e6-9a04-fc221873400e.png)

**Comment by jakewelchert** [comment]
Implemented SEOmatic which is much more robust. All info for Global meta information is now in the SEOmatic tab.
